sudo: required
services:
  - docker
before_install:
  - docker build -t anandatwork/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run anandatwork/react-test npm test -- --coverage

after_success:
  - docker build -t anandatwork/multi-client ./client
  - docker build -t anandatwork/multi-nginx ./nginx
  - docker build -t anandatwork/multi-server ./server
  - docker build -t anandatwork/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push anandatwork/multi-client
  - docker push anandatwork/multi-nginx
  - docker push anandatwork/multi-server
  - docker push anandatwork/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-246002962276
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY


   
